# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='author_mail',
            new_name='author_email',
        ),
    ]
